# Generated by Django 3.0.4 on 2020-03-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Type',
            field=models.CharField(default='customer', max_length=15),
        ),
    ]
